spring.application.name=medication-tracker-backend
spring.datasource.url=jdbc:mysql://localhost:3306/medication_db
spring.datasource.username=root
spring.datasource.password=anubama@123#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
jwt.secret=86f7ab803f6cbf340ad4705f2c83eb73fce1867d09657dcc37098ead60ce37de
server.port=8080



